using System;
using System.Collections.Generic;
using System.Text;

namespace URSdk
{
    public enum MessageSource : int
    {
        MESSAGE_SOURCE_UNDEFINED = -1,
        MESSAGE_SOURCE_JOINT_0 = 0,
        MESSAGE_SOURCE_JOINT_1 = 1,
        MESSAGE_SOURCE_JOINT_2 = 2,
        MESSAGE_SOURCE_JOINT_3 = 3,
        MESSAGE_SOURCE_JOINT_4 = 4,
        MESSAGE_SOURCE_JOINT_5 = 5,
        MESSAGE_SOURCE_TOOL = 6,
        MESSAGE_SOURCE_EUROMAP_2 = 68,
        MESSAGE_SOURCE_EUROMAP_1 = 67,
        MESSAGE_SOURCE_TEACH_PENDANT_2 = 66,
        MESSAGE_SOURCE_TEACH_PENDANT_1 = 65,

        MESSAGE_SOURCE_JOINT_0_FPGA = 100,
        MESSAGE_SOURCE_JOINT_0_A = 110,
        MESSAGE_SOURCE_JOINT_0_B = 120,
        MESSAGE_SOURCE_JOINT_1_FPGA = 101,
        MESSAGE_SOURCE_JOINT_1_A = 111,
        MESSAGE_SOURCE_JOINT_1_B = 121,
        MESSAGE_SOURCE_JOINT_2_FPGA = 102,
        MESSAGE_SOURCE_JOINT_2_A = 112,
        MESSAGE_SOURCE_JOINT_2_B = 122,
        MESSAGE_SOURCE_JOINT_3_FPGA = 103,
        MESSAGE_SOURCE_JOINT_3_A = 113,
        MESSAGE_SOURCE_JOINT_3_B = 123,
        MESSAGE_SOURCE_JOINT_4_FPGA = 104,
        MESSAGE_SOURCE_JOINT_4_A = 114,
        MESSAGE_SOURCE_JOINT_4_B = 124,
        MESSAGE_SOURCE_JOINT_5_FPGA = 105,
        MESSAGE_SOURCE_JOINT_5_A = 115,
        MESSAGE_SOURCE_JOINT_5_B = 125,
        MESSAGE_SOURCE_TOOL_FPGA = 106,
        MESSAGE_SOURCE_TOOL_A = 116,
        MESSAGE_SOURCE_TOOL_B = 126,
        MESSAGE_SOURCE_EUROMAP_FPGA = 107,
        MESSAGE_SOURCE_EUROMAP_A = 117,
        MESSAGE_SOURCE_EUROMAP_B = 127,
        MESSAGE_SOURCE_TEACH_PENDANT_A = 108,
        MESSAGE_SOURCE_TEACH_PENDANT_B = 118,
        MESSAGE_SOURCE_SCB_FPGA = 40,

        MESSAGE_SAFETY_PROCESSOR_UA = 20,
        MESSAGE_SAFETY_PROCESSOR_UB = 30,
        MESSAGE_SOURCE_ROBOTINTERFACE = -2,
        MESSAGE_SOURCE_RTMACHINE = -3,
        MESSAGE_SOURCE_SIMULATED_ROBOT = -4,
        MESSAGE_SOURCE_GUI = -5,
        MESSAGE_SOURCE_CONTROLLER = 7,
        MESSAGE_SOURCE_RTDE = 8,

    }
    public enum MessageType:int
    { 

        RobotState=16,

        RobotMessage=20,//primaryClientOnly

         
    }
}
